config/routes.rb
Rails.application.routes.draw do
  resources :answers
  
  resources :questions do
    member do
      put "check", to: "questions#check"
    end
    resource :answers
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render plain: "Hello, Hero!!!"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @question = Question.all.sample
    
    @true_answer = @question.answer

    @preliminary_choices = []

    Answer.all.sample(6).map do |a| 
      if a.body == @true_answer
        puts "do nothing"
      else
        @preliminary_choices << a.body
      end 
    end

    @multiple_choices = @preliminary_choices.sample(3) << @true_answer
    @multiple_choices = @multiple_choices.shuffle
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    #@answer = @question.answers.create(:body => "#{@question.answer}")

    respond_to do |format|
      if @question.save
        @question.answers.create(:body => "#{@question.answer}")
        format.html { redirect_to root_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check
    @question = Question.find(params[:id])
    
    respond_to do |format|
      if @question.answer == params["selected_answer"]
        format.html { redirect_to root_path, notice: 'Correct Answer :)' }
      else
        format.html { redirect_to root_path, alert: 'Wrong Answer :(' }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:body, :answer)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {success: "alert-sucess", error: "alert-danger", alert: "alert-warning", notice: "alert-info"}[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages (opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, :class => "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: "close", data: {dismiss: "alert"}) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden'=>true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_for(answer) do |f| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %>
    <%= f.number_field :question_id %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question_id %></td>
        <td><%= answer.body %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/application.haml
!!!
%html
  %head
    %title Quizzy
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 

  %body
    .container
      .row
        .col-md-8.col-md-offset-2
          .panel.panel-default
            .panel-body
              .text-center
                .col-md-12
                  = link_to "<i class=\"fa fa-plus fa-fw fa-lg\" style=\"\"></i>New Question".html_safe, new_question_path, :class => "btn btn-success"
                  %br
                  %br
                  = link_to "<i class=\"fa fa-plus fa-fw fa-lg\" style=\"\"></i>Take Quiz".html_safe, questions_path, :class => "btn btn-info"
      .row
        .col-md-8.col-md-offset-2
          = flash_messages
          -#- flash.each do |name, msg|
            - if msg.is_a?(String)
              = content_tag :div, msg, :class => "alert alert-info fade in"
      .row
        = yield

app/views/questions/_check.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-body
        .text-center  
          = form_for question, url: check_question_path(question.id), method: :put do |f|
            %h3
              = question.body

            - choices.each do |c|
              = radio_button_tag(:selected_answer, c)
              = label_tag(:c, "#{c}")
              = "  "

            %br
            = f.button :submit, class: "btn btn-primary" #creates the button to submit

app/views/questions/_form.haml
= simple_form_for @question, html: {multipart: true} do |f|
  - if @question.errors.any?
    #error_explanation
      %h2
        = pluralize(@question.errors.count, "error") #for errors presentation
        prevented this Question from saving
      %ul
        - @question.errors.full_messages.each do |msg|
          %li=msg

  .form-group
    = f.input :body, label:false, input_html: { class: 'form-control'}, placeholder: "Details of your question"
  .form-group
    = f.input :answer, label:false, input_html: { class: 'form-control'}, placeholder: "Your answer"

  = f.button :submit, class: "btn btn-primary" #creates the button to submit

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.haml
= render 'check' , question: @question, answer: @true_answer, choices: @multiple_choices

app/views/questions/new.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Question
      .panel-body
        = render 'form'
        /= render 'form', question: @question
        %br
        = link_to 'Back', questions_path

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>